language: cpp

git:
  depth: false

os:
  - linux
    dist: xenial
    addons:
      apt:
        packages:
          - ncurses-dev
  - osx
    addons:
      homebrew:
        packages:
          ncurses-dev

compiler:
  - gcc
  - clang

script:
  - cmake -S . -B build && cmake --build build
  - echo "q" | build/src/graph
