language: cpp

git:
  depth: false

dist:
- xenial
- trusty

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - ncurses-dev
#  homebrew:
#    packages:
#    - ncurses-dev

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build

script:
  - cmake ..
  - cmake --build .
  - echo "q" | src/graph
